modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
[[mods]]
modId="simplyutilities"
version="${file.jarVersion}"
displayName="Simply Utilities"
# logoFile="examplemod.png" #optional
credits="" #optional
authors="Flanks255"
description='''
A collection of small commands and useful things.
'''
