modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT"
[[mods]]
modId="simplyutilities"
version="${mod_version}"
displayName="Simply Utilities"
# logoFile="examplemod.png" #optional
credits="" #optional
authors="Flanks255"
description='''
A collection of small commands and useful things.
'''
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"